### PR TITLE
fix: node 6 compatibility, take 2 (#355)

### LINKED ISSUE #351: Doesn't work on node 6
(v1.2.0, of course, has "main" as a TS file, so it breaks everywhere) v1.2.1 breaks on node 6 with a syntax error, which is a breaking change in a minor version. I think perhaps you're using exponentiation (`a ** b`) when `Math.pow(a, b)` would serve.

Additionally, v1.0.0+ uses `.padStart`, which is unavailable in node 6 - you can use https://npmjs.com/string.prototype.padstart for this.

Please fix this ASAP, so react-dates can continue depending on this package. I'll be happy to make a PR.

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #351.

### CODE REVIEW

File: src/toHex.ts [hunk 1]
```diff
@@ -6,7 +6,18 @@ import guard from './guard';
  */
 function toHex(color: string): string {
   const [r, g, b, a] = parseToRgba(color);
-  const hex = (x: number) => guard(0, 255, x).toString(16).padStart(2, '0');
+
+  let hex = (x: number) => {
+    const h = guard(0, 255, x).toString(16).padStart(2, '0');
```
Comment (ricokahler) [inline src/toHex.ts]: sneaky `padStart` is still in there haha

File: src/toHex.ts [hunk 2]
```diff
@@ -6,7 +6,18 @@ import guard from './guard';
...
+    // NOTE: padStart could be used here but it breaks Node 6 compat
+    // https://github.com/ricokahler/color2k/issues/351
+    let prefix = '';
+    for (let i = 0; i < 2 - h.length; i++) {
+      prefix += '0';
+    }
```
Comment (ricokahler) [inline src/toHex.ts]: i know this was the solution i opted for in the previous PR however since this is only padding it by one character i think this would be a simpler solution:

```ts
const hex = (x: number) => {
  const h = guard(0, 255, x).toString(16);
  return h.length === 1 ? `0${h}` : h;
};
```

File: src/toHex.ts (hunk 1 above)
Comment (ljharb) [reply src/toHex.ts]: lol whoops, one sec
